# Generated by Django 2.2 on 2020-10-05 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='name',
            new_name='Judul',
        ),
        migrations.RemoveField(
            model_name='task',
            name='deskripsi',
        ),
    ]
