# Generated by Django 2.2 on 2020-10-05 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_auto_20201005_1027'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='Judul',
            new_name='judul',
        ),
    ]
