# Generated by Django 2.2 on 2020-10-06 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0003_auto_20201005_1035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='judul',
            field=models.CharField(max_length=255),
        ),
    ]
